# This is a config for E2B sandbox template.
# You can use template ID (r48fjf6o2m4px7w4y7q7) or template name (justcopy-fullstack-skeleton) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("justcopy-fullstack-skeleton") # Sync sandbox
# sandbox = await AsyncSandbox.create("justcopy-fullstack-skeleton") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('justcopy-fullstack-skeleton')

team_id = "028873ac-ca94-41ac-b974-c5a35444e410"
dockerfile = "e2b.Dockerfile"
template_name = "justcopy-fullstack-skeleton"
template_id = "r48fjf6o2m4px7w4y7q7"
